### ISSUE TITLE
HashTagTestで`downcase' for nil:NilClassとなり失敗する

### ISSUE THREAD

**Issue by karasugawasu** [pooza/mulukhiya-toot-proxy#2019]
## 概要
HashTagTestで`downcase' for nil:NilClassとなり失敗する

## 現象
テストを実行すると以下のエラーが発生する。
```
========================================================================================================================
Error: test_create_feed(Mulukhiya::HashTagTest): NoMethodError: undefined method `downcase' for nil:NilClass
/home/hogeuser/mulukhiya-misskey-proxy/app/lib/mulukhiya/model/misskey/hash_tag.rb:26:in `get'
/home/hogeuser/mulukhiya-misskey-proxy/test/hash_tag.rb:6:in `setup'
========================================================================================================================
E
========================================================================================================================
Error: test_listable?(Mulukhiya::HashTagTest): NoMethodError: undefined method `downcase' for nil:NilClass
/home/hogeuser/mulukhiya-misskey-proxy/app/lib/mulukhiya/model/misskey/hash_tag.rb:26:in `get'
/home/hogeuser/mulukhiya-misskey-proxy/test/hash_tag.rb:6:in `setup'
========================================================================================================================
E
========================================================================================================================
Error: test_name(Mulukhiya::HashTagTest): NoMethodError: undefined method `downcase' for nil:NilClass
/home/hogeuser/mulukhiya-misskey-proxy/app/lib/mulukhiya/model/misskey/hash_tag.rb:26:in `get'
/home/hogeuser/mulukhiya-misskey-proxy/test/hash_tag.rb:6:in `setup'
========================================================================================================================
E
========================================================================================================================
Error: test_raw_name(Mulukhiya::HashTagTest): NoMethodError: undefined method `downcase' for nil:NilClass
/home/hogeuser/mulukhiya-misskey-proxy/app/lib/mulukhiya/model/misskey/hash_tag.rb:26:in `get'
/home/hogeuser/mulukhiya-misskey-proxy/test/hash_tag.rb:6:in `setup'
========================================================================================================================
E
========================================================================================================================
Error: test_to_h(Mulukhiya::HashTagTest): NoMethodError: undefined method `downcase' for nil:NilClass
/home/hogeuser/mulukhiya-misskey-proxy/app/lib/mulukhiya/model/misskey/hash_tag.rb:26:in `get'
/home/hogeuser/mulukhiya-misskey-proxy/test/hash_tag.rb:6:in `setup'
========================================================================================================================
E
========================================================================================================================
Error: test_uri(Mulukhiya::HashTagTest): NoMethodError: undefined method `downcase' for nil:NilClass
/home/hogeuser/mulukhiya-misskey-proxy/app/lib/mulukhiya/model/misskey/hash_tag.rb:26:in `get'
/home/hogeuser/mulukhiya-misskey-proxy/test/hash_tag.rb:6:in `setup'
========================================================================================================================
```

## 期待される動作

テストに失敗しない

## 再現手順
1. bundle exec rake testの実行

### Misskey
CentOS 7.9
ruby 3.0.0p0
Bundler version 2.2.4
mulukhiya-toot-proxy 4.2.2
Misskey v12.74.0

### Pleroma
Ubuntu 20.10
ruby 3.0.0p0
Bundler version 2.2.11
mulukhiya-toot-proxy 4.2.2
Pleroma 2.3.0

すみません、報告遅くなりましたが、
少し前のバージョンから発生していました。

情報不足していましたらお知らせください。

**Comment by pooza** [comment]
デフォルトタグがある環境を前提でテストしている様です。
