### ISSUE TITLE
テスト時のエラー(失敗)について

### ISSUE THREAD

**Issue by karasugawasu** [pooza/mulukhiya-toot-proxy#2253]
## 概要

失敗するテストについての質問になります。
Mastodonでテストした際にStatusTestに失敗します。
（Pleromaでは起きず）

結構前から起きていたので今更の報告ですが、設定ミスなどそのあたりご教示ください。

## 現象
・media_tagのテストで失敗します
　なお、メディアタグの設定はfalseにしています
・StatusTestが複数失敗します
　

テスト結果のログをそのまま張ります。
そのほか必要な情報ありましたらお知らせください・・・

```
====================================================================================================================================================================
Failure: test_media_tag(Mulukhiya::FeedControllerTest):
  <false> expected but was
  <true>
/home/hogeuser/mulukhiya-toot-proxy/test/feed_controller.rb:66:in `test_media_tag'
     63:         end
     64:       else
     65:         get '/tag/image'
  => 66:         assert_false(last_response.ok?)
     67:         assert_equal(last_response.status, 403)
     68:         assert_equal(last_response.content_type, 'application/atom+xml; charset=UTF-8')
     69:
====================================================================================================================================================================
..........................................................................E
====================================================================================================================================================================
Error: test_account(Mulukhiya::StatusTest): NoMethodError: undefined method `account' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:16:in `test_account'
     13:     end
     14:
     15:     def test_account
  => 16:       assert_kind_of(account_class, @status.account)
     17:     end
     18:
     19:     def test_attachments
====================================================================================================================================================================
E
====================================================================================================================================================================
Error: test_attachments(Mulukhiya::StatusTest): NoMethodError: undefined method `attachments' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:20:in `test_attachments'
     17:     end
     18:
     19:     def test_attachments
  => 20:       @status.attachments.each do |attachment|
     21:         assert_kind_of([attachment_class, Hash], attachment)
     22:       end
     23:     end
====================================================================================================================================================================
E
====================================================================================================================================================================
Error: test_id(Mulukhiya::StatusTest): NoMethodError: undefined method `id' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:8:in `test_id'
      5:     end
      6:
      7:     def test_id
  =>  8:       assert(@status.id.present?)
      9:     end
     10:
     11:     def test_to_h
====================================================================================================================================================================
E
====================================================================================================================================================================
Error: test_local?(Mulukhiya::StatusTest): NoMethodError: undefined method `local?' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:26:in `test_local?'
     23:     end
     24:
     25:     def test_local?
  => 26:       assert_boolean(@status.local?)
     27:     end
     28:
     29:     def test_visible?
====================================================================================================================================================================
E
====================================================================================================================================================================
Error: test_public_uri(Mulukhiya::StatusTest): NoMethodError: undefined method `public_uri' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:42:in `test_public_uri'
     39:     end
     40:
     41:     def test_public_uri
  => 42:       assert_kind_of(Ginseng::URI, @status.public_uri)
     43:     end
     44:
     45:     def test_to_md
====================================================================================================================================================================
E
====================================================================================================================================================================
Error: test_text(Mulukhiya::StatusTest): NoMethodError: undefined method `text' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:34:in `test_text'
     31:     end
     32:
     33:     def test_text
  => 34:       assert_kind_of(String, @status.text)
     35:     end
     36:
     37:     def test_uri
====================================================================================================================================================================
.E
====================================================================================================================================================================
Error: test_to_md(Mulukhiya::StatusTest):
  NoMethodError: undefined method `to_md' for nil:NilClass
  Did you mean?  to_d
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:46:in `test_to_md'
     43:     end
     44:
     45:     def test_to_md
  => 46:       assert_kind_of(String, @status.to_md)
     47:     end
     48:   end
     49: end
====================================================================================================================================================================
E
====================================================================================================================================================================
Error: test_uri(Mulukhiya::StatusTest): NoMethodError: undefined method `uri' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:38:in `test_uri'
     35:     end
     36:
     37:     def test_uri
  => 38:       assert_kind_of(Ginseng::URI, @status.uri)
     39:     end
     40:
     41:     def test_public_uri
====================================================================================================================================================================
E
====================================================================================================================================================================
Error: test_visible?(Mulukhiya::StatusTest): NoMethodError: undefined method `visible?' for nil:NilClass
/home/hogeuser/mulukhiya-toot-proxy/test/status.rb:30:in `test_visible?'
     27:     end
     28:
     29:     def test_visible?
  => 30:       assert_boolean(@status.visible?)
     31:     end
     32:
     33:     def test_text
====================================================================================================================================================================
.......................................................................
Finished in 258.112678221 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
343 tests, 842 assertions, 1 failures, 10 errors, 0 pendings, 0 omissions, 0 notifications
96.793% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

## 環境
Mastodon v3.4.1
mulukhiya-toot-proxy 4.5.13

**Comment by pooza** [comment]
`/agent/test/token` からテストボットのアカウントが特定できておらず、テストボットの権限に依存するテストが全て失敗していると考えられます。
関係しているのは[MastodonのAccountモデル](https://github.com/pooza/mulukhiya-toot-proxy/blob/master/app/lib/mulukhiya/model/mastodon/account.rb)にあるMulukhiya::Mastodon::Account#getメソッドです。

`/agent/test/token` のトークンは、

- どんな方法で作られましたか？
  - こちらの想定は、[設置の手順](https://github.com/pooza/mulukhiya-toot-proxy/wiki/%E8%A8%AD%E7%BD%AE%E3%81%AE%E6%89%8B%E9%A0%86)通りモロヘイヤHOMEから作成する手順です。
- [SQL](https://github.com/pooza/mulukhiya-toot-proxy/blob/master/app/query/mastodon/token_owner.sql.erb)を実行して、アカウントIDを特定することが出来ていますか？

**Comment by karasugawasu** [comment]
＞どんな方法で作られましたか？
設置の手順通りやっています、作り直しても同じものでした

＞SQLを実行して
1行の表示がありました。（数字です）

**Comment by pooza** [comment]
実際にはアカウントIDを特定できたSQLが実行できていない可能性があります。

以下追記。
```
postgres:
  query_log: true
```
本番環境でもクエリーログが採れる様になります。
この状態で、クエリー前後のsyslogを採ってみてください。いま実行したのと同じSQLが実行されていますか？

**Comment by karasugawasu** [comment]
[こちらのクエリ](https://github.com/pooza/mulukhiya-toot-proxy/blob/master/app/query/mastodon/recent_toot.sql.erb)で失敗していることがわかりました。

前にクレームが来たという話を聞いてから、テスト実行中でも公開の投稿を削除してたのが原因みたいですね。
とりあえず、消さずに実行したら動きました・・

お騒がせしました。

**Comment by pooza** [comment]
事情理解しました。クエリーログが役に立った様で、実装して良かったですw
開発環境で常時オンはやりすぎなので、オフに戻しておいてくださいね。

少ししたらこの件はクローズします。
