### ISSUE TITLE
特定の投稿をブックマーク時にLemmyに投稿されない

### ISSUE THREAD

**Issue by karasugawasu** [pooza/mulukhiya-toot-proxy#2979]
## 概要
特定の投稿をブックマークした際に、Lemmyに投稿されない

## 現象

Mastodon側で以下のノートをブックマーク、エラーがでてLemmyに投稿できない
https://reco.shrieker.net/notes/71803f6c4f4650e68b6fff0b

Reco鯖の他の投稿も同様

それらしきログ
```
Apr 19 18:00:21 mstdn04sv mulukhiya-toot-proxy[1753]: {"class":"Faye::WebSocket::Client","url":"wss://lm.korako.me/api/v3/ws","payload":{"op":"Login","data":{"username_or_email":"karasu_sue","password":"ababababababab"}}}
Apr 19 18:00:21 mstdn04sv mulukhiya-toot-proxy[1753]: {"method":"POST","url":"https://reco.shrieker.net/api/notes/show","status":200,"seconds":0.245}
Apr 19 18:00:21 mstdn04sv mulukhiya-toot-proxy[1753]: {"class":"Faye::WebSocket::Client","url":"wss://lm.korako.me/api/v3/ws","payload":{"op":"CreatePost","data":{"nsfw":false,"community_id":69,"auth":"abababababaaaba","url":"https://reco.shrieker.net/notes/71803f6c4f4650e68b6fff0b","name":"EPGStation<E3><82><80><E3><81><91><E3><81><AB><E4><BB><8A><E3><81><BE><E3><81><A7><E4><BD><9C><E3><81><A3><E3><81><9F><E5><8D><98><E7><99><BA><E3><82><B9><E3><82><AF><E3><83><AA><E3><83><97><E3><83><88>
<E3><82><92><E3><80><81><E3><83><91><E3><83><83><E3><82><B1><E3><83><BC><E3><82><B8><E3><81><AB><E3><81><BE><E3><81><A8><E3><82><81><E3><81><A6><E3><81><BE><E3><81><99><E3><80><82>tomato-shrieker<E3><81><A8>
<E4><BD><B5><E7><94><A8><E3><81><97><E3><81><A6><E3><80><81><E9><8C><B2><E7><94><BB><E6><83><85><E5><A0><B1><E3><82><92><E6><8A><95><E7><A8><BF><E3><81><99><E3><82><8B><E3><83><9C><E3><83><83><E3><83><88><E3><82><92><E4><BD><9C><E3><81><A3><E3><81><9F><E3><82><8A><E3><81><99><E3><82><8B><E3><81><AE><E3><81><AB><E4><BD><BF><E3><81><84><E3><81><BE><E3><81><99><E3><80><82>\n\nhttps://gi<E2><80><A6>","body":"https://reco.shrieker.net/notes/71803f6c4f4650e68b6fff0b"}}}
Apr 19 18:00:22 mstdn04sv mulukhiya-toot-proxy[1751]: {"daemon":"SidekiqDaemon","ts":"2022-04-19T09:00:22.021Z","pid":1753,"tid":"atil","lvl":"INFO","msg":"Adding dead Mulukhiya::LemmyClippingWorker job 22254988c4b0e5c758e13027","ctx":{"class":"Mulukhiya::LemmyClippingWorker","jid":"22254988c4b0e5c758e13027"}}
Apr 19 18:00:22 mstdn04sv mulukhiya-toot-proxy[1751]: {"daemon":"SidekiqDaemon","ts":"2022-04-19T09:00:22.022Z","pid":1753,"tid":"atil","lvl":"INFO","msg":"fail","ctx":{"class":"Mulukhiya::LemmyClippingWorker","jid":"22254988c4b0e5c758e13027","elapsed":0.663}}
Apr 19 18:00:22 mstdn04sv mulukhiya-toot-proxy[1751]: {"daemon":"SidekiqDaemon","ts":"2022-04-19T09:00:22.022Z","pid":1753,"tid":"atil","lvl":"WARN","msg":"{\"context\":\"Job raised exception\",\"job\":{\"retry\":3,\"queue\":\"default\",\"class\":\"Mulukhiya::LemmyClippingWorker\",\"args\":[{\"uri\":\"https://reco.shrieker.net/notes/71803f6c4f4650e68b6fff0b\",\"account_id\":1}],\"jid\":\"22254988c4b0e5c758e13027\",\"created_at\":1650358717.0496294,\"enqueued_at\":1650358821.3591099,\"error_message\":\"undefined method `[]' for nil:NilClass\\n\\n          raise payload['error'] if payload['error']\\n                                           ^^^^^^^^^\",\"error_class\":\"NoMethodError\",\"failed_at\":1650358718.104278,\"retry_count\":2,\"retried_at\":1650358783.5388505},\"jobstr\":\"{\\\"retry\\\":3,\\\"queue\\\":\\\"default\\\",\\\"class\\\":\\\"Mulukhiya::LemmyClippingWorker\\\",\\\"args\\\":[{\\\"uri\\\":\\\"https://reco.shrieker.net/notes/71803f6c4f4650e68b6fff0b\\\",\\\"account_id\\\":1}],\\\"jid\\\":\\\"22254988c4b0e5c758e13027\\\",\\\"created_at\\\":1650358717.0496294,\\\"enqueued_at\\\":1650358821.3591099,\\\"error_message\\\":\\\"undefined method `[]' for nil:NilClass\\\\n\\\\n          raise payload['error'] if payload['error']\\\\n                                           ^^^^^^^^^\\\",\\\"error_class\\\":\\\"NoMethodError\\\",\\\"failed_at\\\":1650358718.104278,\\\"retry_count\\\":2,\\\"retried_at\\\":1650358783.5388505}\"}"}
Apr 19 18:00:22 mstdn04sv mulukhiya-toot-proxy[1751]: {"daemon":"SidekiqDaemon","ts":"2022-04-19T09:00:22.023Z","pid":1753,"tid":"atil","lvl":"WARN","msg":"NoMethodError: undefined method `[]' for nil:NilClass\n\n          raise payload['error'] if payload['error']\n                                           ^^^^^^^^^"}
Apr 19 18:00:22 mstdn04sv mulukhiya-toot-proxy[1751]: {"daemon":"SidekiqDaemon","ts":"2022-04-19T09:00:22.023Z","pid":1753,"tid":"atil","lvl":"WARN","msg":"/home/mstdn-sue/mulukhiya-toot-proxy/app/lib/mulukhiya/service/lemmy_clipper.rb:69:in `block (2 levels) in listen'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:38:in `each'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:38:in `emit'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/faye-websocket-ruby-0a0e46ab42c1/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/faye-websocket-ruby-0a0e46ab42c1/lib/faye/websocket/api.rb:116:in `receive_message'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/faye-websocket-ruby-0a0e46ab42c1/lib/faye/websocket/api.rb:45:in `block in initialize'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:38:in `each'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:38:in `emit'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/hybi.rb:408:in `emit_message'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/hybi.rb:390:in `emit_frame'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/hybi.rb:118:in `parse'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/websocket-driver-0.7.5/lib/websocket/driver/client.rb:63:in `parse'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/faye-websocket-ruby-0a0e46ab42c1/lib/faye/websocket/api.rb:160:in `parse'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/faye-websocket-ruby-0a0e46ab42c1/lib/faye/websocket/client.rb:110:in `receive_data'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'\n/home/mstdn-sue/mulukhiya-toot-proxy/app/lib/mulukhiya/service/lemmy_clipper.rb:60:in `listen'\n/home/mstdn-sue/mulukhiya-toot-proxy/app/lib/mulukhiya/service/lemmy_clipper.rb:49:in `clip'\n/home/mstdn-sue/mulukhiya-toot-proxy/app/lib/mulukhiya/worker/lemmy_clipping_worker.rb:13:in `perform'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:196:in `execute_job'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:163:in `block in process'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:114:in `local'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq.rb:40:in `block in <module:Sidekiq>'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:257:in `stats'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:13:in `call'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:81:in `global'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:124:in `block in dispatch'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:39:in `prepare'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:123:in `dispatch'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:162:in `process'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:78:in `process_one'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:68:in `run'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:56:in `watchdog'\n/home/mstdn-sue/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:65:in `block in safe_thread'"}
Apr 19 18:01:10 mstdn04sv mulukhiya-toot-proxy[1758]: {"request":{"method":"GET","path":"/api/v2/search","params":{"q":"https://reco.shrieker.net/notes/71803f6c4f4650e68b6fff0b","resolve":"true","limit":"100"},"remote":"172.70.222.40"}}
Apr 19 18:01:10 mstdn04sv mulukhiya-toot-proxy[1758]: {"method":"GET","url":"https://md.korako.me/api/v2/search?limit=100&q=https%3A%2F%2Freco.shrieker.net%2Fnotes%2F71803f6c4f4650e68b6fff0b&resolve=true&version=2","status":200,"seconds":0.503}
```

## 期待される動作

ブックマークした投稿がLemmyにポストできる

## 再現手順

1.Mastodonで該当ノートをブックマーク

## 環境
mulukhiya-toot-proxy 4.17.4
Lemmy：0.16.3 lm.korako.me
Mastodon：3.5.1

**Comment by pooza** [comment]
Lemmyエントリのタイトル（name）に、以下のものが含まれるケースに対処しました。

- 改行
- 壊れたURL
