### ISSUE TITLE
Misskey v13で新規構築時に起動しない

### ISSUE THREAD

**Issue by karasugawasu** [pooza/mulukhiya-toot-proxy#3365]
## 概要

最速設置手順にて設定後、エラーが発生し起動しない。

## 現象
以下のエラーが発生

```
$ bundle exec rake restart
rake aborted!
NoMethodError: undefined method `info_token' for nil:NilClass
/home/user/mulukhiya-toot-proxy/app/lib/mulukhiya/daemon/listener_daemon.rb:22:in `disable?'
/home/user/mulukhiya-toot-proxy/app/lib/mulukhiya/environment.rb:156:in `reject'
/home/user/mulukhiya-toot-proxy/app/lib/mulukhiya/environment.rb:156:in `daemon_classes'
/home/user/mulukhiya-toot-proxy/app/lib/mulukhiya/environment.rb:160:in `task_prefixes'
/home/user/mulukhiya-toot-proxy/app/task/mulukhiya/daemons.rb:30:in `block in <module:Mulukhiya>'
/home/user/mulukhiya-toot-proxy/app/task/mulukhiya/daemons.rb:28:in `each'
/home/user/mulukhiya-toot-proxy/app/task/mulukhiya/daemons.rb:28:in `<module:Mulukhiya>'
/home/user/mulukhiya-toot-proxy/app/task/mulukhiya/daemons.rb:1:in `<top (required)>'
/home/user/mulukhiya-toot-proxy/app/lib/mulukhiya.rb:65:in `block in load_tasks'
/home/user/mulukhiya-toot-proxy/app/lib/mulukhiya.rb:65:in `each'
/home/user/mulukhiya-toot-proxy/app/lib/mulukhiya.rb:65:in `load_tasks'
/home/user/mulukhiya-toot-proxy/Rakefile:5:in `<top (required)>'
/home/user/.rbenv/versions/3.2.0/bin/bundle:25:in `load'
/home/user/.rbenv/versions/3.2.0/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
```

## 期待される動作

起動する

## 再現手順

1. 最速設置手順を行う
2. 起動する

なお、通常の設置手順にあるようにinfo/tokenに適当なものを入れておいてもNG、lintも同様のエラーで動かず
```
agent:
  info:
    token: foo
  test:
    tokan: bar
```

Mastodonインスタンスのものと比較してみたがそこまでおかしいところはなさそう・・？
Misskeyの問題なのかおまかんなのか、設定の問題か不明。

## 環境
Mulukhiya: v4.26.0
Misskey: 13.6.1
OS: Oracle Linux 8

**Comment by pooza** [comment]
Misskey鯖がまだ準備できておらず、実機確認ができていません。（準備中）
エラーから察すると、ListenerDaemon#disable?でEnvironment.account_classがnilらしいです。通常の設置ではちょっと考えにくい状況です。

ListenerDaemon#disable? の動作を確認、必要ならパッチを当てる予定。
